# Generated by Django 3.1.3 on 2021-01-23 13:30

from django.db import migrations, models
import splash_screen.models


class Migration(migrations.Migration):

    dependencies = [
        ('splash_screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='splash',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=splash_screen.models.upload_path),
        ),
    ]
