# Generated by Django 3.1.3 on 2021-01-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash_screen', '0002_splash_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splash',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='splash',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
