# Generated by Django 3.1.3 on 2021-01-25 02:53

from django.db import migrations, models
import splash_screen.models


class Migration(migrations.Migration):

    dependencies = [
        ('splash_screen', '0004_auto_20210124_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splash',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=splash_screen.models.upload_path),
        ),
    ]
